plugins {
    id 'java'
    id 'application'
    id 'com.github.alexeylisyutenko.windows-service-plugin' version '1.1.0'
}

group = 'com.github.moaxcp.spyware'
version = '1.0'

repositories {
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

application {
    mainClass = 'com.github.moaxcp.spyware.Main'
}

jar {
    manifest {
        attributes 'Main-Class': 'com.github.moaxcp.spyware.Main' // Replace with your actual main class
    }
}

test {
    useJUnitPlatform()
}

windowsService {
    architecture = 'AMD64'
    displayName = 'Screenshot Service'
    description = 'Service to take screenshots'
    startClass = 'com.github.moaxcp.spyware.Main'
    startMethod = 'main'
    startup = 'auto'
    interactive = true
    pidFile = 'pid.txt'
    logPath = '%APP_HOME%\\logs'
    logPrefix = 'spyware'
    stdOutput = 'auto'
    stdError = 'auto'
}