plugins {
    id 'java'
    id 'application'
}

group = 'com.github.moaxcp.spyware'
version = '1.0'

repositories {
    mavenCentral()
    gradlePluginPortal()
}

dependencies {
    testImplementation platform('org.junit:junit-bom:5.10.0')
    testImplementation 'org.junit.jupiter:junit-jupiter'
}

application {
    mainClass = 'com.github.moaxcp.spyware.Main'
}

jar {
    manifest {
        attributes 'Main-Class': 'com.github.moaxcp.spyware.Main' // Replace with your actual main class
    }
}

test {
    useJUnitPlatform()
}